# Setup
name:         "Programování pro biology"
tagline:      "Úvod do práce s příkazovým řádkem a programování v Pythonu"
baseurl:      "/intro_python_biol"

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
